sudo: required
services:
  - docker

before_install:
  - docker build -t achordia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run achordia/react-test npm run test -- --coverage

after_success:
  - docker build -t achordia/multi-client ./client
  - docker build -t achordia/multi-nginx ./nginx
  - docker build -t achordia/multi-server ./server
  - docker build -t achordia/multi-worker ./worker

#Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub 
  - docker push achordia/multi-client
  - docker push achordia/multi-nginx
  - docker push achordia/multi-server
  - docker push achordia/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "DockerDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-120371544090"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"